"""Delete all existing papers/chunks and re-ingest from papers/ directory.

Usage:
    cd apps/api
    python -m scripts.reingest_all
"""

import asyncio
import logging

from src.core.ingestion import ingest_paper
from src.db import get_supabase
from src.schema.rag import PaperMetadata

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# Metadata for all 34 papers
PAPERS = [
    # --- Original 9 papers (Phases 1-3) ---
    {
        "filename": "nutrients-13-01915.pdf",
        "title": "Creatine for Exercise and Sports Performance, with Recovery Considerations for Healthy Populations",
        "authors": "Wax et al.",
        "year": 2021,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu13061915",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8228369/",
    },
    {
        "filename": "nutrients-17-02748.pdf",
        "title": "The Effects of Creatine Supplementation on Upper- and Lower-Body Strength and Power in Healthy Adults: A Systematic Review with Meta-Analysis",
        "authors": "Kazeminasab et al.",
        "year": 2025,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "meta-analysis",
        "doi": "10.3390/nu17172748",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12430374/",
    },
    {
        "filename": "ijerph-16-04897.pdf",
        "title": "Maximizing Muscle Hypertrophy: A Systematic Review of Advanced Resistance Training Techniques and Methods",
        "authors": "Krzysztofik et al.",
        "year": 2019,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "International Journal of Environmental Research and Public Health",
        "study_type": "systematic-review",
        "doi": "10.3390/ijerph16244897",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6950543/",
    },
    {
        "filename": "fspor-04-949021.pdf",
        "title": "Resistance Training Variables for Optimization of Muscle Hypertrophy: An Umbrella Review",
        "authors": "Bernardez-Vazquez et al.",
        "year": 2022,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Frontiers in Sports and Active Living",
        "study_type": "systematic-review",
        "doi": "10.3389/fspor.2022.949021",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9302196/",
    },
    {
        "filename": "sports-09-00032.pdf",
        "title": "Loading Recommendations for Muscle Strength, Hypertrophy, and Local Endurance: A Re-Examination of the Repetition Continuum",
        "authors": "Schoenfeld et al.",
        "year": 2021,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Sports",
        "study_type": "review",
        "doi": "10.3390/sports9020032",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7927075/",
    },
    {
        "filename": "sports-08-00125.pdf",
        "title": "Tapering and Peaking Maximal Strength for Powerlifting Performance: A Review",
        "authors": "Travis et al.",
        "year": 2020,
        "category": "strength",
        "license": "CC-BY",
        "journal": "Sports",
        "study_type": "review",
        "doi": "10.3390/sports8090125",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7552788/",
    },
    {
        "filename": "fspor-03-713655.pdf",
        "title": "The Minimum Effective Training Dose Required for 1RM Strength in Powerlifters",
        "authors": "Androulakis-Korakakis et al.",
        "year": 2021,
        "category": "strength",
        "license": "CC-BY",
        "journal": "Frontiers in Sports and Active Living",
        "study_type": "review",
        "doi": "10.3389/fspor.2021.713655",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8435792/",
    },
    {
        "filename": "jscr-34-2412.pdf",
        "title": "Long-Term Strength Adaptation: A 15-Year Analysis of Powerlifting Athletes",
        "authors": "Latella et al.",
        "year": 2020,
        "category": "strength",
        "license": "CC-BY",
        "journal": "Journal of Strength and Conditioning Research",
        "study_type": "observational",
        "doi": "10.1519/JSC.0000000000003657",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7448836/",
    },
    {
        "filename": "40279_2019_Article_1241.pdf",
        "title": "The Effectiveness of Two Methods of Prescribing Load on Maximal Strength Development: A Systematic Review",
        "authors": "Thompson et al.",
        "year": 2020,
        "category": "strength",
        "license": "CC-BY",
        "journal": "Sports Medicine",
        "study_type": "systematic-review",
        "doi": "10.1007/s40279-019-01241-3",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7142036/",
    },
    # --- 10 new hypertrophy papers (corpus expansion) ---
    {
        "filename": "fspor-06-1429789.pdf",
        "title": "Rest Interval Duration and Hypertrophy: A Bayesian Meta-Analysis",
        "authors": "Singer et al.",
        "year": 2024,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Frontiers in Sports and Active Living",
        "study_type": "meta-analysis",
        "doi": "10.3389/fspor.2024.1429789",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11349676/",
    },
    {
        "filename": "jfmk-09-00009.pdf",
        "title": "Optimizing Resistance Training Technique to Maximize Muscle Hypertrophy: A Narrative Review",
        "authors": "Androulakis Korakakis et al.",
        "year": 2024,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Journal of Functional Morphology and Kinesiology",
        "study_type": "review",
        "doi": "10.3390/jfmk9010009",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10801605/",
    },
    {
        "filename": "40279_2021_Article_1465.pdf",
        "title": "The Influence of Movement Tempo During Resistance Training on Muscular Strength and Hypertrophy Responses: A Review",
        "authors": "Wilk et al.",
        "year": 2021,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Sports Medicine",
        "study_type": "review",
        "doi": "10.1007/s40279-021-01465-2",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8310485/",
    },
    {
        "filename": "40279_2022_Article_1784.pdf",
        "title": "Influence of Resistance Training Proximity-to-Failure on Skeletal Muscle Hypertrophy: A Systematic Review with Meta-analysis",
        "authors": "Refalo et al.",
        "year": 2023,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Sports Medicine",
        "study_type": "meta-analysis",
        "doi": "10.1007/s40279-022-01784-y",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9935748/",
    },
    {
        "filename": "fphys-10-00013.pdf",
        "title": "Periodization Models for Optimizing Strength and Hypertrophy",
        "authors": "Evans",
        "year": 2019,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Frontiers in Physiology",
        "study_type": "review",
        "doi": "10.3389/fphys.2019.00013",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6351492/",
    },
    {
        "filename": "peerj-05-3695.pdf",
        "title": "The Effects of Linear and Daily Undulating Periodized Resistance Training Programs on Measures of Muscle Hypertrophy: A Systematic Review and Meta-Analysis",
        "authors": "Grgic et al.",
        "year": 2017,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "PeerJ",
        "study_type": "meta-analysis",
        "doi": "10.7717/peerj.3695",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5571788/",
    },
    {
        "filename": "40279_2023_Article_1898.pdf",
        "title": "Physiology of Stretch-Mediated Hypertrophy and Strength Increases: A Narrative Review",
        "authors": "Warneke et al.",
        "year": 2023,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Sports Medicine",
        "study_type": "review",
        "doi": "10.1007/s40279-023-01898-x",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10587333/",
    },
    {
        "filename": "fphys-10-00536.pdf",
        "title": "Eccentric Muscle Contractions: Risks and Benefits",
        "authors": "Hody et al.",
        "year": 2019,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Frontiers in Physiology",
        "study_type": "review",
        "doi": "10.3389/fphys.2019.00536",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6510035/",
    },
    {
        "filename": "jfmk-07-00081.pdf",
        "title": "Beyond Mechanical Tension: A Review of Resistance Exercise-Induced Lactate Responses and Muscle Hypertrophy",
        "authors": "Lawson et al.",
        "year": 2022,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Journal of Functional Morphology and Kinesiology",
        "study_type": "review",
        "doi": "10.3390/jfmk7040081",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9590033/",
    },
    {
        "filename": "40279_2021_Article_1490.pdf",
        "title": "No Time to Lift? Designing Time-Efficient Training Programs for Strength and Hypertrophy: A Narrative Review",
        "authors": "Iversen et al.",
        "year": 2021,
        "category": "hypertrophy",
        "license": "CC-BY",
        "journal": "Sports Medicine",
        "study_type": "review",
        "doi": "10.1007/s40279-021-01490-1",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8449772/",
    },
    # --- 15 new nutrition papers (Phase 8) ---
    {
        "filename": "fnut-05-00083.pdf",
        "title": "Effects of Protein Supplementation on Performance and Recovery in Resistance and Endurance Training",
        "authors": "Cintineo et al.",
        "year": 2018,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Frontiers in Nutrition",
        "study_type": "review",
        "doi": "10.3389/fnut.2018.00083",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6142015/",
    },
    {
        "filename": "fnut-11-1455728.pdf",
        "title": "The Effect of Protein Intake on Athletic Performance: A Systematic Review and Meta-Analysis",
        "authors": "Zhao et al.",
        "year": 2024,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Frontiers in Nutrition",
        "study_type": "meta-analysis",
        "doi": "10.3389/fnut.2024.1455728",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11613885/",
    },
    {
        "filename": "TSMED2024-3184356.pdf",
        "title": "Characterisation of the Muscle Protein Synthetic Response to Resistance Exercise in Healthy Adults: A Systematic Review and Exploratory Meta-Analysis",
        "authors": "Davies et al.",
        "year": 2024,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Translational Sports Medicine",
        "study_type": "meta-analysis",
        "doi": "10.1155/2024/3184356",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11074832/",
    },
    {
        "filename": "nutrients-12-02457.pdf",
        "title": "Muscle Protein Synthesis and Whole-Body Protein Turnover Responses to Ingesting Essential Amino Acids, Intact Protein, and Protein-Containing Mixed Meals with Considerations for Energy Deficit",
        "authors": "Gwin et al.",
        "year": 2020,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu12082457",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7469068/",
    },
    {
        "filename": "41430_2022_Article_1250.pdf",
        "title": "The Impact of Dietary Protein Supplementation on Recovery from Resistance Exercise-Induced Muscle Damage: A Systematic Review with Meta-Analysis",
        "authors": "Pearson et al.",
        "year": 2023,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "European Journal of Clinical Nutrition",
        "study_type": "meta-analysis",
        "doi": "10.1038/s41430-022-01250-y",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10393778/",
    },
    {
        "filename": "421_2022_Article_4896.pdf",
        "title": "Lean Mass Sparing in Resistance-Trained Athletes During Caloric Restriction: The Role of Resistance Training Volume",
        "authors": "Roth et al.",
        "year": 2022,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "European Journal of Applied Physiology",
        "study_type": "review",
        "doi": "10.1007/s00421-022-04896-5",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9012799/",
    },
    {
        "filename": "nutrients-12-01948.pdf",
        "title": "Nutrient Timing: A Garage Door of Opportunity?",
        "authors": "Arent et al.",
        "year": 2020,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu12071948",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7400240/",
    },
    {
        "filename": "nutrients-08-00763.pdf",
        "title": "Pre-Sleep Protein Ingestion to Improve the Skeletal Muscle Adaptive Response to Exercise Training",
        "authors": "Trommelen & van Loon",
        "year": 2016,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu8120763",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5188418/",
    },
    {
        "filename": "fnut-06-00017.pdf",
        "title": "The Impact of Pre-sleep Protein Ingestion on the Skeletal Muscle Adaptive Response to Exercise in Humans: An Update",
        "authors": "Snijders et al.",
        "year": 2019,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Frontiers in Nutrition",
        "study_type": "review",
        "doi": "10.3389/fnut.2019.00017",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6415027/",
    },
    {
        "filename": "nutrients-16-03247.pdf",
        "title": "The Top 5 Can't-Miss Sport Supplements",
        "authors": "Antonio et al.",
        "year": 2024,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu16193247",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11479151/",
    },
    {
        "filename": "12970_2018_Article_216.pdf",
        "title": "Effects of Caffeine Intake on Muscle Strength and Power: A Systematic Review and Meta-Analysis",
        "authors": "Grgic et al.",
        "year": 2018,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Journal of the International Society of Sports Nutrition",
        "study_type": "meta-analysis",
        "doi": "10.1186/s12970-018-0216-0",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5839013/",
    },
    {
        "filename": "12970_2015_Article_90.pdf",
        "title": "International Society of Sports Nutrition Position Stand: Beta-Alanine",
        "authors": "Trexler et al.",
        "year": 2015,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Journal of the International Society of Sports Nutrition",
        "study_type": "review",
        "doi": "10.1186/s12970-015-0090-y",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4501114/",
    },
    {
        "filename": "nutrients-16-01886.pdf",
        "title": "Supplementation Strategies for Strength and Power Athletes: Carbohydrate, Protein, and Amino Acid Ingestion",
        "authors": "Bird et al.",
        "year": 2024,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu16121886",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11206787/",
    },
    {
        "filename": "nutrients-13-00294.pdf",
        "title": "Nutrition and Muscle Recovery",
        "authors": "Mielgo-Ayuso & Fernández-Lázaro",
        "year": 2021,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu13020294",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7909540/",
    },
    {
        "filename": "nutrients-11-00822.pdf",
        "title": "Sleep and Nutrition Interactions: Implications for Athletes",
        "authors": "Doherty et al.",
        "year": 2019,
        "category": "nutrition",
        "license": "CC-BY",
        "journal": "Nutrients",
        "study_type": "review",
        "doi": "10.3390/nu11040822",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6520871/",
    },
]


async def main():
    supabase = get_supabase()

    # 1. Delete all existing chunks and papers
    print("Deleting existing chunks...")
    supabase.table("chunks").delete().neq("id", "00000000-0000-0000-0000-000000000000").execute()
    print("Deleting existing papers...")
    supabase.table("papers").delete().neq("id", "00000000-0000-0000-0000-000000000000").execute()
    print("Cleared.\n")

    # 2. Re-ingest all papers
    total_chunks = 0
    for i, entry in enumerate(PAPERS, 1):
        print(f"[{i}/{len(PAPERS)}] {entry['title'][:70]}...")

        metadata = PaperMetadata(
            title=entry["title"],
            authors=entry["authors"],
            year=entry["year"],
            category=entry["category"],
            license=entry["license"],
            journal=entry.get("journal"),
            doi=entry.get("doi"),
            url=entry.get("url"),
            study_type=entry.get("study_type"),
        )

        result = await ingest_paper(f"papers/{entry['filename']}", metadata)
        print(f"  -> {result.total_chunks} chunks")
        total_chunks += result.total_chunks

    print(f"\nDone! {len(PAPERS)} papers, {total_chunks} total chunks.")


if __name__ == "__main__":
    asyncio.run(main())
